networks:
  nginx-proxy-network:
    external: true

volumes:
  portfolio-client:

services:
  portfolio-client:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      network: host
      args:
        NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL}
        STRAPI_TOKEN: ${STRAPI_TOKEN}
        NEXT_PUBLIC_WEBSITE_URL: ${NEXT_PUBLIC_WEBSITE_URL}
    env_file:
      - stack.env
    networks:
      - nginx-proxy-network
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - portfolio-client:/app
      - /app/node_modules
      - /app/.next
